### ISSUE TITLE
Overwrite of some properties not working

### ISSUE THREAD

**Issue by samuelstein** [getgrav/grav-plugin-lightslider#12]
Hello,
i couldn't find a way to overwrite the properties *speed* and *auto*. I changed the values on the slider content page at the user/config/plugins page.

**Comment by flaviocopes** [comment]
This already works. You need to put the change in user/config/plugins/lightslider.yaml or in the page frontmatter

```yaml
lightslider:
  auto: false
```

**Comment by samuelstein** [comment]
if i'm adding this, then i have no autmatic slides changing. my goal was to change the default speed and pause settings.
