### ISSUE TITLE
Admin plugin does not find lightslider template

### ISSUE THREAD

**Issue by Tamriel** [getgrav/grav-plugin-lightslider#22]
> This plugin is provided as a modular page within Grav. That modular page created should be called lightslider.md so that it will automatically use the lightslider twig template already provided in the plugin.

When I add photos to the lightslider.md file with the admin plugin, the file gets renamed to features.md and therefore the slider does not work anymore :(
This is due the admin plugin dos not find the lightslider template, it is not offered in the dropdown menu where one can select the site template.

**Comment by phideas** [comment]
confirming this issue
