### ISSUE TITLE
Can't disable dark layer over slider images

### ISSUE THREAD

**Issue by mrdaak** [getgrav/grav-plugin-lightslider#25]
Plugin puts transparent dark layer by default over images. Couldn't find the corresponding css code or plugin settings.

**Comment by x9e0319** [comment]
I have the same Problem. Have you figured it out ?

**Comment by tutchmedia** [comment]
@mrdaak  @x9e0319 - Did you folks manage to sort this? Having the same problem and seems to be converting the image itself rather than CSS effect...
